apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ads-boost
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
