apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ads-boost
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cmeyr/ads-boost-frontend
          ports:
            - containerPort: 80
              name: http
